### ISSUE TITLE
能增加暂停功能吗?

### ISSUE THREAD

**Issue by wmailn** [qssq/recordutil#1]
能增加暂停功能吗?

**Comment by lozn00** [comment]
哥们 腾讯QQ的录音都没有做这个功能,你们老板是不是有点变态？

**Comment by wmailn** [comment]
这 ..... 还是有些场景需要这个功能的

**Comment by lozn00** [comment]
mp3不太可能，其他的你照着改一改就好了， 可以强转为指定管理器 然后进行暂停，但是 mp3之类的就算了吧。

**Comment by lozn00** [comment]
建议使用工厂的方式，这样切换录音格式只需要改一句工厂代码就行。 RecordFactory

如果要拿到具体的MediaRecorder 类 比如Amr的， 可以直接强转AmrRecorderManager 然后 getMediaRecorder() 就可以实现这个得暂停，这个暂停自己百度就行。

**Comment by wmailn** [comment]
我们是要求AAC格式，AudioRecord是支持暂停的，貌似MediaRecorder不支持暂停？

**Comment by lozn00** [comment]
http://blog.csdn.net/wanli_smile/article/details/7715030

**Comment by wmailn** [comment]
那就要合并文件的路子了 ... 好吧 
多谢回复  我还是看看AudioRecord实时转AAC的方案
