### ISSUE TITLE
内存溢出问题

### ISSUE THREAD

**Issue by chenzixue** [qssq/recordutil#3]
![1198d7ba09c37736d21dcbfe8f82e8c1](https://user-images.githubusercontent.com/13416741/32151857-0b159962-bd5b-11e7-8c87-34221fac9842.png)

**Comment by lozn00** [comment]
是不是没看demo调用停止方法，另外是不是传错上下文了？

**Comment by lozn00** [comment]
setMediaManagerProvider 是在application里面设置的，你不要在activity里面设置，
